#+TITLE: ~/dotfiles/emacs.org
 
* emacs.org
** What is this?
This is my emacs configuration in org-mode using org-babel. It's loaded using =(org-babel-load-file "~/dotfiles/emacs.org")= from my =init.el=. It contains a lot of things inspired (stolen) from places around the on web such as:
- [[http://pages.sachachua.com/.emacs.d/Sacha.html][Sacha Chua's config]]
- [[https://github.com/TheBB/dotemacs][TheBB's config]]
- [[https://github.com/jwiegley/dot-emacs][jwiegly's config]]
- [[https://github.com/syl20bnr/spacemacs][Spacemacs]]
- [[https://github.com/hlissner/doom-emacs][Doom Emacs]]

** How to Add/Modify
To add a code block, type =<s= and press =tab=, this adds a code block. Type =emacs-lisp= after =#BEGIN_SRC= to ensure the correct language.
To modify a code block, press =C-c '= to open an emacs-lisp buffer and hack away. Use =eval-buffer= to test the changes, and press =C-c '= again to add the changes to the org file.
* Emacs
#+BEGIN_SRC emacs-lisp
;;; -*- lexical-binding: t; -*-
#+END_SRC
** Personal Information
Who am I?
#+BEGIN_SRC emacs-lisp
  (setq user-full-name "Kevin Pavao"
        user-mail-address "kpavao84@gmail.com")
#+END_SRC
** Garbage Collection
Modify garbage collection. This is supposed to speed things up a bit.
#+BEGIN_SRC emacs-lisp
  (setq gc-cons-threshold 100000000)
  (defvar gc-timer nil)
  (defun maybe-gc ()
    (let ((original gc-cons-threshold))
      (setq gc-cons-threshold 800000)
      (setq gc-cons-threshold original
            gc-timer (run-with-timer 2 nil #'schedule-maybe-gc))))

  (defun schedule-maybe-gc ()
    (setq gc-timer (run-with-idle-timer 2 nil #'maybe-gc)))

  (schedule-maybe-gc)
#+END_SRC
** Package Setup
Setup the package repositories.
#+BEGIN_SRC emacs-lisp
  (require 'package)
  (setq package-enable-at-startup nil)
  (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
  ;;(add-to-list 'package-archives '("gnu" . "https://elpa.gnu.org/packages/") t)
  ;(add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/") t)
  ;(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)
  ;; (add-to-list 'package-archives
  ;;              '("elpy" . "https://jorgenschaefer.github.io/packages/"))
  (package-initialize)
#+END_SRC

Automatically install and then setup =use-package= and =diminish=
#+BEGIN_SRC emacs-lisp
  (unless (package-installed-p 'use-package)
    (package-refresh-contents)
    (package-install 'use-package))

  (unless (package-installed-p 'diminish)
    (package-install 'diminish))

  (eval-when-compile
    (require 'use-package))
  (require 'diminish) ;; for :diminish
  (require 'bind-key) ;; for :bind
#+END_SRC

=paradox= gives some nicer package management options than the default.
=(paradox-enable)= replaces the =list-packages= command with =paradox-list-packages=.
#+BEGIN_SRC emacs-lisp
  (use-package paradox
    :ensure t
    :config
    (paradox-enable))
#+END_SRC
** Startup
Display the scratch buffer when starting up, use =org-mode= for the scratch buffer, and remove the default message.
#+BEGIN_SRC emacs-lisp
  (setq  inhibit-startup-screen t
         initial-major-mode 'org-mode
         initial-scratch-message nil)
#+END_SRC
** Core
Things that modify or replace the core functionality of Emacs, or are needed by the rest of the config.
*** Saner Defaults
Modify some of the default settings.

Change "yes or no" to "y or n"
#+BEGIN_SRC emacs-lisp
  (fset 'yes-or-no-p 'y-or-n-p)
#+END_SRC

Update buffers automatically when underlying files are changed externally.
#+BEGIN_SRC emacs-lisp
  (global-auto-revert-mode t)
#+END_SRC

Use UTF-8, this should fix flycheck errors with python-flake8
#+BEGIN_SRC emacs-lisp
  (set-default-coding-systems 'utf-8)
#+END_SRC

A package that provides some good defaults, e.g. using the X clipboard for yanking
#+BEGIN_SRC emacs-lisp
  (use-package better-defaults
    :ensure t)
#+END_SRC

Don't create any extra files.
#+BEGIN_SRC emacs-lisp
  (setq make-backup-files nil ; stop creating backup~ files
        auto-save-default nil ; stop creating #autosave# files
        create-lockfiles nil) ; stop creating .# files
#+END_SRC

Create a =~/.emacs.d/etc/= and =~/.emacs.d/var/= to store files and data used by Emacs packages.
#+BEGIN_SRC emacs-lisp
  (use-package no-littering
    :ensure t
    :init
    (setq no-littering-etc-directory
          (expand-file-name "etc/" user-emacs-directory))
    (setq no-littering-var-directory
          (expand-file-name "var/" user-emacs-directory)))
#+END_SRC

*** Vim Emulation
This allows you to use emacs keybindings while in evil's insert mode.
from https://stackoverflow.com/questions/25542097/emacs-evil-mode-how-to-change-insert-state-to-emacs-state-automatically
#+BEGIN_SRC emacs-lisp
  (defun my-emacs-in-normal-mode ()
    (setq evil-insert-state-map (make-sparse-keymap))
    (define-key evil-insert-state-map (kbd "<escape>") 'evil-normal-state))
#+END_SRC

Evil mode is vim in emacs!
#+BEGIN_SRC emacs-lisp
  (use-package evil
    :ensure t
    :init
    (setq evil-want-keybinding nil)  ;; evil-collection assumes this
    (setq evil-want-C-u-scroll t)
    :config
    (evil-mode 1)
    (my-emacs-in-normal-mode))
#+END_SRC

Use evil bindings in various modes.
#+BEGIN_SRC emacs-lisp
  (use-package evil-collection
    :after evil
    :ensure t
    :config
    (evil-collection-init))
#+END_SRC

surround.vim emulation.
#+BEGIN_SRC emacs-lisp
  (use-package evil-surround
    :after evil
    :ensure t
    :config
    (global-evil-surround-mode 1))
#+END_SRC

Show tildes in the fringe on empty lines.
#+BEGIN_SRC emacs-lisp
  (use-package vi-tilde-fringe
    :ensure t
    :config
    (global-vi-tilde-fringe-mode 1))
#+END_SRC
*** Keys
To set up custom keys, I use a combination of:
- =general= - an easier way to define custom keys than the built in one
- =which-key= - shows a list of all available keybindings, it works nicely with =general=, as it will show all the keybindings available after pressing ~SPC~
- =hydra= - create a "mode" (similar to how i3 does resize mode) for repeated actions
- =keyfreq= - use =keyfreq-show= to get a list of most use commands and then make keybindings/hydras out of them
**** general
#+BEGIN_QUOTE
=general.el= provides a more convenient method for binding keys in emacs ... Like =use-package= ...
#+END_QUOTE

This creates a =leader=, which allows you to set up custom keys after pressing a certain key
- Keys for all modes appear after pressing ~SPC~ in normal and visual mode, or ~M-SPC~ in everything else.
- Mode specific keys appear after pressing ~SPC m~ in normal and visual mode, or ~M-,~ in everything else.

It also a =:general= use-package keyword, so this needs to be setup before that is used anywhere.

#+BEGIN_SRC emacs-lisp
  (use-package general
    :ensure t
    :config
    (setq general-override-states '(insert emacs hybrid normal visual motion operator replace))
    (general-override-mode)
    (general-evil-setup)
    (general-create-definer my-leader-def
      :states '(normal visual insert emacs)
      :prefix "SPC"
      :non-normal-prefix "M-SPC")

    (general-create-definer my-local-leader-def
      :states '(normal visual insert emacs)
      :prefix "SPC m"
      :non-normal-prefix "M-,")

    ;; define which-key prefixes
    (my-leader-def
      "p" '(:ignore t :wk "projects")
      "b" '(:ignore t :wk "buffers")
      "w" '(:ignore t :wk "windows")
      "r" '(:ignore t :wk "bookmarks")
      "t" '(:ignore t :wk "terminal")
      "g" '(:ignore t :wk "git")
      "j" '(:ignore t :wk "jump")
      "q" '(:ignore t :wk "quit / restart"))

    (my-leader-def
      "c" 'comment-dwim
      "RET" 'make-frame-command
      "l" 'my/what-minor-mode
      ;; bookmarks
      "rm" 'bookmark-set
      "rb" 'bookmark-jump
      "rl" 'bookmark-bmenu-list
      ;; quit / restart
      "qq" 'save-buffers-kill-terminal
      "qr" 'restart-emacs))
#+END_SRC
**** which-key
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :diminish which-key-mode
    :config
    (which-key-mode)
    (which-key-setup-minibuffer)
    (which-key-setup-side-window-bottom)
    (setq which-key-idle-delay 0)
    ;; (which-key-add-key-based-replacements "SPC w" "windows")
    ;; (which-key-add-key-based-replacements "SPC b" "buffers")
    ;; (which-key-add-key-based-replacements "SPC p" "projects")
    ;; (which-key-add-key-based-replacements "SPC b" "buffers")
    ;; (which-key-add-key-based-replacements "SPC r" "bookmarks")
    ;; (which-key-add-key-based-replacements "SPC t" "terminal")
    ;; (which-key-add-key-based-replacements "SPC g" "magit")
    ;; (which-key-add-key-based-replacements "SPC j" "dumb-jump")
    ;; (which-key-add-key-based-replacements "SPC jg" "go")
    (which-key-add-major-mode-key-based-replacements 'scheme-mode "SPC m e" "eval")
    (which-key-add-major-mode-key-based-replacements 'lisp-interaction-mode "SPC m e" "eval")
    (which-key-add-major-mode-key-based-replacements 'emacs-lispmode "SPC m e" "eval"))
#+END_SRC
**** hydra
#+BEGIN_SRC emacs-lisp
  (use-package hydra
    :ensure t
    :config
    (defhydra hydra-zoom (global-map "<f5>")
      "zoom"
      ("g" text-scale-increase "in")
      ("l" text-scale-decrease "out")
      ("r" (text-scale-set 0) "reset")
      ("0" (text-scale-set 0) :bind nil :exit t)))
#+END_SRC
**** keyfreq
#+BEGIN_SRC emacs-lisp
  (use-package keyfreq
    :ensure t
    :config
    (keyfreq-autosave-mode 1))
#+END_SRC
*** Mouse
Better mouse scrolling - the default scrolling is too quick.
#+BEGIN_SRC emacs-lisp
  (setq scroll-margin 10
        scroll-step 1
        next-line-add-newlines nil
        scroll-conservatively 10000
        scroll-preserve-screen-position 1
        mouse-wheel-follow-mouse 't
        mouse-wheel-scroll-amount '(1 ((shift) . 1)))
#+END_SRC
*** Ivy / Counsel
Some nice tools that use the minibuffer.

#+BEGIN_QUOTE
Ivy, a generic completion mechanism for Emacs.
#+END_QUOTE
#+BEGIN_SRC emacs-lisp
  (use-package ivy
    :ensure t
    :demand t
    :general
    ("<f6>" 'ivy-resume)
    :config
    (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    (setq ivy-count-format "(%d/%d) ")
    (setq ivy-height 20))
#+END_SRC

#+BEGIN_QUOTE
Counsel, a collection of Ivy-enhanced versions of common Emacs commands.
#+END_QUOTE
#+BEGIN_SRC emacs-lisp
  (use-package counsel
    :ensure t
    :after ivy
    :demand t
    :general
    ("M-x" 'counsel-M-x)
    ("C-x C-f" 'counsel-find-file)
    ("<f1> f" 'counsel-describe-function)
    ("<f1> v" 'counsel-describe-variable)
    ("<f1> l" 'counsel-find-library)
    ("<f2> i" 'counsel-info-lookup-symbol)
    ("<f2> u" 'counsel-unicode-char)
    ("C-c g" 'counsel-git)
    ("C-c j" 'counsel-git-grep)
    ("C-c k" 'counsel-rg)
    ("C-x l" 'counsel-locate)
    ("C-S-r" 'counsel-expression-history)
    (my-leader-def
      "f" 'counsel-find-file
      "x" 'counsel-M-x)
    :config
    ;; use ripgrep for counsel-git-grep
    (setq counsel-git-cmd "rg --files")
    (setq counsel-rg-base-command
          "rg -i -M 120 --no-heading --line-number --color never %s ."))
#+END_SRC

#+BEGIN_SRC emacs-lisp
  (use-package counsel-etags
    :after counsel
    :ensure t)
#+END_SRC
*** Search / Replace
**** swiper
Replace keybindings for emacs search and evil search with swiper.
#+BEGIN_SRC emacs-lisp
  (use-package swiper
    :ensure t
    :after ivy
    :general
    ("C-s" 'swiper)
    (evil-normal-state-map "/" 'swiper))
#+END_SRC
**** anzu
Add find and replace info to the modeline.
#+BEGIN_SRC emacs-lisp
  (use-package anzu
    :ensure t
    :config
    (global-anzu-mode)
    (global-set-key [remap query-replace] 'anzu-query-replace)
    (global-set-key [remap query-replace-regexp] 'anzu-query-replace-regexp))
#+END_SRC
*** Undo
Replace standard Emacs undo with =undo-tree=. Press ~C-x u~ to use =undo-tree=. and ~q~ to quit.

This way I can use evil's undo (~u~ in Normal mode) and =undo-tree= at the same time.
#+BEGIN_SRC emacs-lisp
  (use-package undo-tree
    :diminish undo-tree-mode
    :defer t
    :ensure t
    :config
    (setq undo-tree-visualizer-timestamps t)
    (setq undo-tree-visualizer-diff t)
    (global-undo-tree-mode))
#+END_SRC
** Look and Feel
*** Change defaults
Hide the gui and use a non-blinking cursor for a more zen-like experience.
Use C-mouse3 to open the menu-bar as a popup menu
#+BEGIN_SRC emacs-lisp
  (menu-bar-mode -99)
  (tool-bar-mode -1) ;; hide the toolbar
  (scroll-bar-mode -1) ;; hide the scrollbar
  (blink-cursor-mode 0) ;; dont blink the cursor
  (set-fringe-mode '(10 . 0)) ;; remove the extra border around frames
  (global-hl-line-mode 1) ;; highlight the current line
#+END_SRC
*** Theme
Theme I'm currently using
#+BEGIN_SRC emacs-lisp
  (use-package nord-theme
    :ensure t
    :config
    (load-theme 'nord))
   #+END_SRC

Some dark themes I Like
#+BEGIN_SRC emacs-lisp
  ;; (use-package doom-themes
  ;;   :ensure t
  ;;   :init
  ;;   (setq doom-themes-enable-bold t
  ;;         doom-themes-enable-italic t)
  ;;   :config
  ;;   (load-theme 'doom-nord))

  ;; (use-package kaolin-themes
  ;;   :ensure t
  ;;   :init
  ;;   ;; (setq doom-themes-enable-bold t
  ;;   ;;       doom-themes-enable-italic t)
  ;;   (setq kaolin-themes-hl-line-colored t
  ;;         kaolin-themes-italic-comments t)
  ;;   :config
  ;;   ;; (load-theme 'doom-one t)
  ;;   ;; (doom-themes-treemacs-config)
  ;;   ;; (doom-themes-org-config)
  ;;   (load-theme 'kaolin-ocean t)
  ;;   (kaolin-treemacs-theme))


  ;; (use-package poet-theme
  ;;    :ensure t
  ;;    :config
  ;;    (load-theme 'poet-dark))

  ;;  ;; setup different fonts
  ;;  (add-hook 'text-mode-hook
  ;;            (lambda ()
  ;;              (variable-pitch-mode 1)))

  ;;  (set-face-attribute 'default nil :family "Iosevka" :height 130)
  ;;  (set-face-attribute 'fixed-pitch nil :family "Iosevka")
  ;;  (set-face-attribute 'variable-pitch nil :family "ETBookOT")

   ;;(load-theme 'base16-tomorrow-night)
   ;;(load-theme 'kaolin-dark)
   ;;(load-theme 'doom-one)
   ;;(load-theme 'doom-tomorrow-night)
   ;;(load-theme 'doom-city-lights)
   ;;(load-theme 'kaolin-ocean)
   ;; (load-theme 'base16-spacemacs)
   ;;(load-theme 'gruvbox-dark-hard)
   ;;(load-theme 'sourcerer)
   ;;(load-theme 'spacemacs-dark)
   ;;(load-theme 'base16-tomorrow-dark)
   ;;(load-theme 'base16-twilight-dark)
   ;;(load-theme 'base16-default-dark)
   ;;(load-theme 'solarized-dark)
   ;;(setq solarized-distinct-fringe-background t)
   ;;(load-theme 'base16-ocean-dark)
   ;;(load-theme 'material)
   ;;(load-theme 'spacegray)
   ;;(load-theme 'dracula)
   ;;(load-theme 'reykjavik)
   ;;(set-cursor-color "gainsboro")
#+END_SRC

Some light themes I like
#+BEGIN_SRC emacs-lisp
  ;;(load-theme 'spacemacs-light)
  ;;(load-theme 'light-soap)
  ;;(load-theme 'solarized-light)
#+END_SRC
*** Font
Font I'm currently using
#+BEGIN_SRC emacs-lisp
  (add-to-list 'default-frame-alist '(font . "Iosevka-12"))
#+END_SRC

Other fonts I like
#+BEGIN_SRC emacs-lisp
  ;; (add-to-list 'default-frame-alist '(font . "Victor Mono-12"))
  ;; (add-to-list 'default-frame-alist '(font . "Monoid HalfTight-10"))
  ;; (add-to-list 'default-frame-alist '(font . "Monoid-10"))
  ;; (add-to-list 'default-frame-alist '(font . "Hermit-12"))
  ;; (add-to-list 'default-frame-alist '(font . "Lemon-12"))
  ;; (add-to-list 'default-frame-alist '(font . "Uushi-11"))
  ;; (add-to-list 'default-frame-alist '(font . "Cherry-13"))
  ;; (add-to-list 'default-frame-alist '(font . "Scientifica-14" ))
  ;; (add-to-list 'default-frame-alist '(font . "Curie-14" ))
  ;; (add-to-list 'default-frame-alist '(font . "Fira Code-12" ))
  ;; (add-to-list 'default-frame-alist '(font . "Hack-12" ))
  ;; (add-to-list 'default-frame-alist '(font . "Input Mono Narrow-11" ))
  ;; (add-to-list 'default-frame-alist '(font . "Hermit-10" ))
  ;; (add-to-list 'default-frame-alist '(font . "Monaco-10" ))
  ;; (add-to-list 'default-frame-alist '(font . "Fantasque Sans Mono-11" ))
  ;; (add-to-list 'default-frame-alist '(font . "GohuFont-14" ))
  ;; (add-to-list 'default-frame-alist '(font . "envypn-11" ))
#+END_SRC
*** Modeline
**** telephone-line
Set up all the icons
#+BEGIN_SRC emacs-lisp
  (use-package all-the-icons
    :ensure t)
#+END_SRC

this is modified from [[https://github.com/ogdenwebb/snug-emacs][ogdenwebb/snug-emacs]]
#+BEGIN_SRC emacs-lisp
  (use-package telephone-line
    :ensure t
    :hook (after-init . telephone-line-mode)
    :config
    ;; (setq telephone-line-primary-left-separator 'telephone-line-flat
    ;;       telephone-line-secondary-left-separator 'telephone-line-flat
    ;;       telephone-line-primary-right-separator 'telephone-line-flat
    ;;       telephone-line-secondary-right-separator 'telephone-line-flat)

    (setq telephone-line-primary-left-separator 'telephone-line-abs-left
          telephone-line-secondary-left-separator 'telephone-line-abs-hollow-left
          telephone-line-primary-right-separator 'telephone-line-abs-right
          telephone-line-secondary-right-separator 'telephone-line-abs-hollow-right)

    (defface my-accent-active
      '((t (:foreground "#ECEFF4" :background "#3B4252" :inherit mode-line)))
      "Accent face for mode-line."
      :group 'telephone-line)

    (defface my-blue-accent
      '((t (:foreground "#ECEFF4" :background "#5E81AC" :inherit mode-line)))
      "Accent face for mode-line."
      :group 'telephone-line)

    (defface my-line-evil-insert
      '((t (:background "#A3BE8C" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Insert state."
      :group 'telephone-line-evil)

    (defface my-line-evil-normal
      '((t (:background "#5E81AC" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Normal state."
      :group 'telephone-line-evil)

    (defface my-line-evil-visual
      '((t (:background "#D08770" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Visual{,-Block,-Line} state."
      :group 'telephone-line-evil)

    (defface my-line-evil-replace
      '((t (:background "black" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Replace state."
      :group 'telephone-line-evil)

    (defface my-line-evil-motion
      '((t (:background "dark blue" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Motion state."
      :group 'telephone-line-evil)

    (defface my-line-evil-operator
      '((t (:background "#B48EAD" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Operator state."
      :group 'telephone-line-evil)

    (defface my-line-evil-emacs
      '((t (:background "dark violet" :inherit telephone-line-evil)))
      "Face used in evil color-coded segments when in Emacs state."
      :group 'telephone-line-evil)

    (defun my-evil-face (active)
      "Return an appropriate face for the current mode, given whether the frame is ACTIVE."
      (cond ((not active) 'mode-line-inactive)
            (t (intern (concat "my-line-evil-" (symbol-name evil-state))))))

    (setq telephone-line-faces
          '((evil . my-evil-face)
            (accent my-accent-active . mode-line-inactive)
            (blue-accent my-blue-accent . mode-line-inactive)
            (nil mode-line . mode-line-inactive)))

    (setq modeline-ignored-modes '("Warnings"
                                   "Compilation"
                                   "EShell"
                                   "Debugger"
                                   "REPL"
                                   "IELM"
                                   "Messages"))

    (setq telephone-line-height 20)

    (telephone-line-defsegment my-evil-segment ()
      "Display evil state as text symbol."
      (let ((tag (cond
                  ((string= evil-state "normal")    "<N>")
                  ((string= evil-state "insert")    "<I>")
                  ((string= evil-state "replace")   "<R>")
                  ((string= evil-state "visual")    "<V>")
                  ((string= evil-state "operator")  "<O>")
                  ((string= evil-state "motion")    "<M>")
                  ((string= evil-state "emacs")     "<E>")
                  ((string= evil-state "multiedit") "<ME>")
                  (t "-"))))
        (format "%s" tag)))

    (telephone-line-defsegment* my-major-mode-segment-icon ()
      "Display the name of the major mode along with an icon representing the major mode."
      (let ((icon (all-the-icons-icon-for-mode major-mode :v-adjust 0.0 :height 0.8 :face font-lock-string-face)))
        (concat
         (when
             (and (not (eq major-mode (all-the-icons-icon-for-mode major-mode)))
                  (telephone-line-selected-window-active))
           (format "%s " icon))
         (propertize mode-name 'face `font-lock-string-face))))

    (telephone-line-defsegment* my-major-mode-segment ()
      "Display the name of the major mode."
      (propertize mode-name 'face `font-lock-string-face))

    (telephone-line-defsegment my-modified-status-segment ()
      "Display if the buffer has been saved or not."
      (when (and (buffer-modified-p) (not (member mode-name modeline-ignored-modes)) (not buffer-read-only))
        (format "%s "
                (propertize (all-the-icons-faicon "pencil")
                            'face `(:height 1.0 :foreground "#EBCB8B")
                            'display '(raise 0.0)))))

    (telephone-line-defsegment my-buffer-segment ()
      "Display the path to the current file.
  If in a project, concatenate the paths up to the project and highlight the project name.
  e.g. ~/p/projectname/file.scm"
      (cond ((and (fboundp 'projectile-project-name)
                  (fboundp 'projectile-project-p)
                  (projectile-project-p))
             (list ""
                   (propertize
                    (telephone-line--truncate-path ;; the path to the project
                     (abbreviate-file-name (file-name-directory (directory-file-name (projectile-project-root)))) 1)
                    'face `(:foreground "#81A1C1")
                    'help-echo (buffer-file-name))
                   (funcall (telephone-line-projectile-segment) face)
                   (propertize
                    (concat "/" (file-relative-name (file-truename (buffer-file-name)) (projectile-project-root)))
                    'help-echo (buffer-file-name))))
            ((buffer-file-name)
             (propertize (file-truename (buffer-file-name))
                         'help-echo (buffer-file-name)))
            (t
             (propertize
              (format "%s" (telephone-line-raw mode-line-buffer-identification t))))))

    (telephone-line-defsegment my-selection-info-segment ()
      "Information about the size of the current selection, when applicable.
      Supports both Emacs and Evil cursor conventions."
      (when (or mark-active
                (and (bound-and-true-p evil-local-mode)
                     (eq 'visual evil-state)))
        (let* ((lines (count-lines (region-beginning) (region-end)))
               (chars (- (1+ (region-end)) (region-beginning)))
               (evil (and (bound-and-true-p evil-state) (eq 'visual evil-state)))
               (rect (or (bound-and-true-p rectangle-mark-mode)
                         (and evil (eq 'block evil-visual-selection))))
               (multi-line (or (> lines 1) (and evil (eq 'line evil-visual-selection)))))
          (cond (multi-line
                 (propertize
                  (format " %dc:%dL" (if evil chars (1- chars)) lines)
                  'face `(:foreground "#81A1C1")))
                (t
                 (propertize
                  (format " %dc" (if evil chars (1- chars)))
                  'face `(:foreground "#81A1C1")))))))

    (defadvice vc-mode-line (after strip-backend () activate)
      "Hide 'Git:' from the vc segment"
      (when (stringp vc-mode)
        (let ((my-vc (replace-regexp-in-string "^ Git." "" vc-mode)))
          (setq vc-mode my-vc))))

    (telephone-line-defsegment my-vc-segment ()
      (when (and vc-mode
                 (telephone-line-selected-window-active))
        ;; double format to prevent warnings in '*Messages*' buffer
        (format "%s %s"
                (propertize (format "%s" (all-the-icons-octicon "git-branch"))
                            'face `(:family ,(all-the-icons-octicon-family) :height 1.0 :foreground ,(face-foreground 'font-lock-variable-name-face))
                            'display '(raise 0.0))
                (propertize
                 (format "%s"
                         (telephone-line-raw vc-mode t))
                 'face `(:foreground ,(face-foreground 'font-lock-variable-name-face))))))

    (setq telephone-line-lhs
          '((evil   . (my-evil-segment))
            (accent . (my-major-mode-segment-icon
                       telephone-line-erc-modified-channels-segment
                       telephone-line-process-segment))
            (nil    . (my-modified-status-segment
                       telephone-line-filesize-segment
                       my-buffer-segment
                       my-selection-info-segment))))
    (setq telephone-line-rhs
          '((nil         . (telephone-line-misc-info-segment))
            (accent      . (my-vc-segment
                            telephone-line-flycheck-segment
                            telephone-line-airline-position-segment))
            (blue-accent . (telephone-line-atom-encoding-segment)))))
#+END_SRC
**** doom modeline
*NOTE* You need to run =M-x all-the-icons-install-fonts= to get the fancy fonts in the modeline
#+BEGIN_SRC emacs-lisp
  ;; (use-package all-the-icons
  ;;   :ensure t)

  ;; (defun my-doom-modeline-hook ()
  ;;   (column-number-mode)
  ;;   (doom-modeline-init))

  ;; (use-package doom-modeline
  ;;   :ensure t
  ;;   :defer t
  ;;   :hook (after-init . my-doom-modeline-hook))
#+END_SRC
**** spaceline
Add an animated nyan-cat to indicate the buffer position, because why not?
#+BEGIN_SRC emacs-lisp
  ;; (use-package nyan-mode
  ;;   :ensure t
  ;;   :init
  ;;   (setq nyan-wavy-trail t)
  ;;   :config
  ;;   (nyan-mode 1)
  ;;   (nyan-start-animation))
#+END_SRC

spacemacs modeline settings
#+BEGIN_SRC emacs-lisp
  ;; (use-package spaceline
  ;;   :ensure t)

  ;; (use-package spaceline-config
  ;;   :ensure spaceline
  ;;   :config
  ;;   ;; (setq powerline-default-separator 'wave)
  ;;   ;; (setq powerline-default-separator 'alternate)
  ;;   ;; (setq powerline-default-separator 'arrow)
  ;;   ;; (setq powerline-default-separator 'arrow-fade)
  ;;   ;; (setq powerline-default-separator 'box)
  ;;   ;; (setq powerline-default-separator 'brace)
  ;;   ;; (setq powerline-default-separator 'butt)
  ;;   ;; (setq powerline-default-separator 'chamfer)
  ;;   ;; (setq powerline-default-separator 'contour)
  ;;   ;; (setq powerline-default-separator 'curve)
  ;;   ;; (setq powerline-default-separator 'rounded)
  ;;   ;; (setq powerline-default-separator 'roundstub)
  ;;   ;; (setq powerline-default-separator 'wave)
  ;;   ;; (setq powerline-default-separator 'zigzag)
  ;;   ;; (setq powerline-default-separator 'utf-8)

  ;;   (setq powerline-default-separator 'bar)
  ;;   (spaceline-spacemacs-theme)
  ;;   (setq spaceline-highlight-face-func 'spaceline-highlight-face-evil-state)
  ;;   (setq spaceline-workspace-numbers-unicode t)
  ;;   (setq spaceline-window-numbers-unicode t))
#+END_SRC

**** My custom modeline
#+BEGIN_SRC emacs-lisp
  ;; (setq-default mode-line-format
  ;;               (list
  ;;      "-- "
  ;;      ;; the buffer name; the file name as a tool tip
  ;;      '(:eval (propertize "%b " 'face 'font-lock-keyword-face
  ;;                         'help-echo (buffer-file-name)))

  ;;     ;; the current major mode for the buffer.
  ;;      "["

  ;;      '(:eval (propertize "%m" 'face 'font-lock-string-face
  ;;                          'help-echo buffer-file-coding-system))
  ;;      " -"
  ;;      minor-mode-alist ;; the minor modes for the current buffer
  ;;      "] "

  ;;      "[" ;; insert vs overwrite mode, input-method in a tooltip
  ;;      '(:eval (propertize (if overwrite-mode "Ovr" "Ins")
  ;;             'face 'font-lock-preprocessor-face
  ;;             'help-echo (concat "Buffer is in "
  ;;                             (if overwrite-mode "overwrite" "insert") " mode")))

  ;;      ;; was this buffer modified since the last save?
  ;;      '(:eval (when (buffer-modified-p)
  ;;             (concat ","  (propertize "Mod"
  ;;             'face 'font-lock-warning-face
  ;;                               'help-echo "Buffer has been modified"))))

  ;;      ;; is this buffer read-only?
  ;;      '(:eval (when buffer-read-only
  ;;                (concat ","  (propertize "RO"
  ;;                               'face 'font-lock-type-face
  ;;                               'help-echo "Buffer is read-only"))))
  ;;      "] "

  ;;      ;; line and column
  ;;      "(" ;; '%02' to set to 2 chars at least; prevents flickering
  ;;        (propertize "%02l" 'face 'font-lock-type-face) ","
  ;;        (propertize "%02c" 'face 'font-lock-type-face)
  ;;      ") "

  ;;      ;; '(:eval (list (nyan-create)))

  ;;      ;; relative position, size of file
  ;;      "["
  ;;      (propertize "%p" 'face 'font-lock-constant-face) ;; % above top
  ;;      ;;"/"
  ;;      ;;(propertize "%I" 'face 'font-lock-constant-face) ;; size
  ;;      "] "

  ;;      " %-" ;; fill with '-'
  ;;      ))
#+END_SRC

****** TODO make the color of the bar change when switching between evil modes
#+BEGIN_SRC emacs-lisp
  ;; change mode-line color by evil state
  ;;(lexical-let ((default-color (cons (face-background 'mode-line)
  ;;                                  (face-foreground 'mode-line))))
  ;;    (add-hook 'post-command-hook
  ;;    (lambda ()
  ;;      (let ((color (cond ((minibufferp) default-color)
  ;;                      ((evil-insert-state-p) '("#eee" . "#ffffff"))
  ;;                      ((evil-emacs-state-p)  '("#444488" . "#ffffff"))
  ;;                      ((buffer-modified-p)   '("#006fa0" . "#ffffff"))
  ;;                      (t default-color))))
  ;;      (set-face-background 'mode-line (car color))
  ;;      (set-face-foreground 'mode-line (cdr color))))))
#+END_SRC
*** solaire
make certain buffers lighter/darker, e.g. treemacs
#+BEGIN_SRC emacs-lisp
  ;; (use-package solaire-mode
  ;;   :ensure t
  ;;   :hook ((change-major-mode after-revert ediff-prepare-buffer) . turn-on-solaire-mode)
  ;;   :config
  ;;   (add-hook 'minibuffer-setup-hook #'solaire-mode-in-minibuffer)
  ;;   (solaire-mode-swap-bg))
#+END_SRC
*** rainbow delimiters
Add rainbow delimiters in all programming language modes
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :hook (prog-mode . rainbow-delimiters-mode))
#+END_SRC
*** Other stuff
Add a space between the line numbers and the text
From https://www.emacswiki.org/emacs/LineNumbers
#+BEGIN_SRC emacs-lisp
  ;; (add-hook 'linum-before-numbering-hook
  ;;           (lambda ()
  ;;             (setq-local linum-format-fmt
  ;;                         (let ((w (length (number-to-string
  ;;                                           (count-lines (point-min) (point-max))))))
  ;;                           (concat "%" (number-to-string w) "d")))))

  ;; (defun linum-format-func (line)
  ;;   (concat
  ;;    (propertize (format linum-format-fmt line) 'face 'linum)
  ;;    (propertize " " 'face 'mode-line)))

  ;; (setq linum-format 'linum-format-func)
#+END_SRC

Remove black stuff around the edges
#+BEGIN_SRC emacs-lisp
  (setq frame-resize-pixelwise t)
#+END_SRC
** Custom Functions
*** what-minor-mode
list minor modes
- =my-active-minor-modes= is from: https://stackoverflow.com/questions/1511737/how-do-you-list-the-active-minor-modes-in-emacs
- =my/active-minor-modes= is =doom/what-minor-mode= from https://github.com/hlissner/doom-emacs
  + it uses =my-active-minor-modes= for the list of minor modes to display
#+BEGIN_SRC emacs-lisp
  (defun my-active-minor-modes ()
    "Get a list of active minor-mode symbols."
    (delq nil
          (mapcar
           (lambda (x)
             (let ((car-x (car x)))
               (when (and (symbolp car-x) (symbol-value car-x))
                 x)))
           minor-mode-alist)))

  (defun my/what-minor-mode (mode)
    "Get information on an active minor mode. Use `describe-minor-mode' for a
  selection of all minor-modes, active or not."
    (interactive
     (list (completing-read "Minor mode: "
                            (my-active-minor-modes))))
    (describe-minor-mode-from-symbol
     (cl-typecase mode
       (string (intern mode))
       (symbol mode)
       (t (error "Expected a symbol/string, got a %s" (type-of mode))))))
#+END_SRC
** Window and Buffer Management
*** Keys
#+BEGIN_SRC emacs-lisp
  (my-leader-def
    "c" 'comment-dwim
    "RET" 'make-frame-command
    "l" 'my/what-minor-mode
    ;; buffers and windows
    "bb" 'switch-to-buffer
    "bk" 'kill-buffer
    "wo" 'split-window-horizontally
    "wu" 'split-window-vertically
    "wd" 'delete-window
    "wh" 'windmove-left
    "wj" 'windmove-down
    "wk" 'windmove-up
    "wl" 'windmove-right
    "w." 'eyebrowse-switch-to-window-config
    "w," 'eyebrowse-rename-window-config
    "w1" 'eyebrowse-switch-to-window-config-1
    "w2" 'eyebrowse-switch-to-window-config-2
    "w3" 'eyebrowse-switch-to-window-config-3
    "w4" 'eyebrowse-switch-to-window-config-4
    "w4" 'eyebrowse-switch-to-window-config-4
    "w5" 'eyebrowse-switch-to-window-config-5
    "w6" 'eyebrowse-switch-to-window-config-6
    "w7" 'eyebrowse-switch-to-window-config-7
    "w8" 'eyebrowse-switch-to-window-config-8
    "w9" 'eyebrowse-switch-to-window-config-9
    "w0" 'eyebrowse-switch-to-window-config-0)
#+END_SRC
*** eyebrowse
Eyebrowse provides a way to manage workspaces like tiling window managers.
#+BEGIN_SRC emacs-lisp
  (use-package eyebrowse
    :ensure t
    :config
    (eyebrowse-mode t))
#+END_SRC
*** windmove
Windmove provides a way to move around emacs windows.

Default keybindings are: S-arrowkey (e.g. S-Left) to move around
#+BEGIN_SRC emacs-lisp
  (windmove-default-keybindings)
#+END_SRC
** Project and File Management
*** dired
#+BEGIN_SRC emacs-lisp
  (use-package dired
    :hook (dired-mode . dired-hide-details-mode)
    :config
    ;; Colourful columns.
    (use-package diredfl
      :ensure t
      :config
      (diredfl-global-mode 1)))
#+END_SRC

Press ~C-(~ to get git info
#+BEGIN_SRC emacs-lisp
  (use-package dired-git-info
      :ensure t
      :bind (:map dired-mode-map
                  ("C-(" . dired-git-info-mode)))
#+END_SRC
*** projectile
Projectile allows some nice things for projects, such as searching for files, managing buffers, etc.
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :config
    (projectile-global-mode))

  (use-package counsel-projectile
    :ensure t
    :after (counsel projectile)
    :general
    (my-leader-def
      "pf" 'counsel-projectile-find-file
      "pd" 'counsel-projectile-find-dir
      "pb" 'counsel-projectile-switch-to-buffer
      "pp" 'counsel-projectile-switch-project
      "pg" 'counsel-projectile-rg) ;;ripgrep
    :config
    (counsel-projectile-mode))
#+END_SRC
*** treemacs
A file tree.
#+BEGIN_SRC emacs-lisp
  (use-package treemacs
    :ensure t
    :general ([f8] 'treemacs))

  (use-package treemacs-evil
    :ensure t
    :after (evil treemacs))

  (use-package treemacs-projectile
    :ensure t
    :after (projectile treemacs))
#+END_SRC
** Org Mode
Set up everything for =org-mode=
*** Prettify
Stuff for making org-mode prettier:
- =org-src-fontify-natively= turns on syntax highlighting for =#+SRC= blocks
#+BEGIN_SRC emacs-lisp
  (defun my-org-prettify ()
    (setq org-src-fontify-natively t)
    ;; (custom-set-faces
    ;;  '(org-level-1 ((t (:inherit outline-1 :height 1.3))))
    ;;  '(org-level-2 ((t (:inherit outline-1 :height 1.2))))
    ;;  '(org-level-3 ((t (:inherit outline-1 :height 1.1))))
    ;;  '(org-level-4 ((t (:inherit outline-1 :height 1.0))))
    ;;  '(org-level-5 ((t (:inherit outline-1 :height 1.0)))))
    )
#+END_SRC
**** htmlize
Provides syntax highlighting for =#+SRC= blocks in html exports.

Needed by =pelican= and =nikola=
#+BEGIN_SRC emacs-lisp
  (use-package htmlize
    :ensure t)
#+END_SRC
*** Setup for TODOs
Setup for TODO items.
Change the status of the todo state by pressing =C-c C-c t <KEY>=
- the =<KEY>= is the the letter in the parens after the state (e.g. =TODO(t)=)

The todo states are largely based taken from from http://doc.norang.ca/org-mode.html
#+BEGIN_SRC emacs-lisp
  (defun my-org-todo-setup ()
    (setq org-todo-keywords
          '((sequence "TODO(t)" "NEXT(n)" "CURRENT(c)" "|" "DONE(d)")
            (sequence "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)")))
    (setq org-todo-keyword-faces
          (quote (("TODO" :foreground "#ff5555" :weight bold)
                  ("NEXT" :foreground "#61bfff" :weight bold)
                  ("CURRENT" :foreground "#8be9fd" :weight bold)
                  ("DONE" :foreground "#50fa7b" :weight bold)
                  ("WAITING" :foreground "orange" :weight bold)
                  ("HOLD" :foreground "#ff79c6" :weight bold)
                  ("CANCELLED" :foreground "forest green" :weight bold))))
    (setq org-use-fast-todo-selection t)
    ;; insert time/date when moved to DONE
    (setq org-log-done 'time))
#+END_SRC
*** Structure Templates
Add structure templates, e.g. type <el ~TAB~ for =#+BEGIN_SRC emacs-lisp #+END_SRC=
Existing templates for reference:
- https://orgmode.org/manual/Easy-templates.html
#+BEGIN_SRC emacs-lisp
  (defun my-structure-templates ()
    (add-to-list 'org-structure-template-alist '("el" "#+BEGIN_SRC emacs-lisp\n\n#+END_SRC"))
    (add-to-list 'org-structure-template-alist '("sh" "#+BEGIN_SRC sh\n\n#+END_SRC")))
#+END_SRC
*** Use Package Setup
=my-org-mode-hook= enables:
- =indent-mode= indents each header and text block
- =org-bullets= provides prettier bullets for the header
- =turn-on-visual-line-mode= is for visual word wrap

Put it all together. The =:general= block maps ~:x~ and ~:q~ to confirm and ~:q~ to abort when editing =SRC= blocks.
#+BEGIN_SRC emacs-lisp
  (use-package org
    :ensure org-bullets
    :preface
    (defun my-org-mode-hook ()
      (org-indent-mode)
      (turn-on-visual-line-mode)
      (setq org-bullets-bullet-list
            '("◉" "○"))
      (org-bullets-mode 1))
    :general
    (org-src-mode-map
     [remap evil-save-and-close]          'org-edit-src-exit
     [remap evil-save-modified-and-close] 'org-edit-src-exit
     [remap evil-quit]                    'org-edit-src-abort)
    (my-leader-def
      "a" 'org-agenda)
    (my-local-leader-def 'org-mode-map
      "t" 'org-babel-tangle)
    :hook (org-mode . my-org-mode-hook)
    :config
    (my-org-todo-setup)
    (my-org-prettify)
    (my-structure-templates)
    (setq org-agenda-files (list "~/org/agenda/")))
#+END_SRC
**** old stuff
old snippets of things
#+BEGIN_SRC emacs-lisp
  ;; (font-lock-add-keywords 'org-mode
  ;;                         '(("^ +\\([-*]\\) "
  ;;                            (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

  ;; (setq org-todo-keywords
  ;;       '((sequence "TODO" "CURRENT" "|" "DONE")))

  ;; (font-lock-add-keywords 'org-mode
  ;;                         '(("^ +\\([-*]\\) "
  ;;                            (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))

                                          ;(setq org-hide-emphasis-markers t)
#+END_SRC
*** Org Babel Languages
Enable python for in-buffer evaluation
#+BEGIN_SRC emacs-lisp
  (org-babel-do-load-languages
   'org-babel-load-languages
   '((python . t)))
#+END_SRC
** Code
Things that are used when coding.
*** Line Numbers
Add line numbers everywhere
#+BEGIN_SRC emacs-lisp
  (add-hook 'prog-mode-hook 'display-line-numbers-mode)
  ;;(global-display-line-numbers-mode)
#+END_SRC
*** flycheck
Error checking.
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :diminish flycheck-mode
    :ensure t
    :config
    (global-flycheck-mode))
#+END_SRC
*** company
Company provides code completion.
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :config
    (global-company-mode))
#+END_SRC

*** language server protocol
Setup for Microsoft's (GASP!) Language Server Protocol.

#+BEGIN_QUOTE
The Language Server Protocol (LSP) defines the protocol used between an editor or IDE and a language server that provides language features like auto complete, go to definition, find all references etc.
#+END_QUOTE

#+BEGIN_SRC emacs-lisp
  (use-package company-lsp
    ;; :after (company-mode)
    :ensure t)

  (use-package lsp-ui
    :after (flycheck-mode)
    :ensure t)

  (use-package lsp-mode
    :ensure t
    :config
    (require 'lsp-clients))

  ;; lsp extras
  ;; (use-package lsp-ui
  ;;   :ensure t
  ;;   :after (lsp-mode)
  ;;   :hook (lsp-mode . lsp-ui-mode)
  ;;   :config
  ;;   (setq lsp-ui-sideline-ignore-duplicate t
  ;;         lsp-ui-flycheck-enable t))

  ;; (use-package company-lsp
  ;;   :ensure t
  ;;   :after (lsp-mode company-mode)
  ;;   :config
  ;;   (push 'company-lsp company-backends))
#+END_SRC
*** smartparens
autocomplete for brackets
#+BEGIN_SRC emacs-lisp
  (use-package smartparens
    :ensure t
    ;; :config
    ;; (add-hook 'python-mode-hook (function (lambda ()
    ;;                                         (smartparens-mode t))))
    )
#+END_SRC
*** dumb-jump
Get some nice go-to-definition functionality
#+BEGIN_SRC emacs-lisp
  (use-package dumb-jump
    :ensure t
    :general
    ("M-g o" 'dumb-jump-go-other-window)
    ("M-g j" 'dumb-jump-go)
    ("M-g i" 'dumb-jump-go-prompt)
    ("M-g x" 'dumb-jump-go-prefer-external)
    ("M-g z" 'dumb-jump-go-prefer-external-other-window)
    ("<f9>"  'dumb-jump-hydra/body)
    (my-leader-def
      "jg" '(:ignore t :wk "go")
      "jgg" 'dumb-jump-go
      "jgc" 'dumb-jump-go-current-window
      "jgo" 'dumb-jump-go-other-window
      "jgp" 'dumb-jump-go-prefer-external
      "jgP" 'dumb-jump-go-prefer-external-other-window
      "jgp" 'dumb-jump-go-prompt
      "jb" 'dumb-jump-back
      "jq" 'dumb-jump-quick-look)
    :config
    (setq dumb-jump-selector 'ivy)
    (setq dumb-jump-force-searcher 'rg)
    (defhydra dumb-jump-hydra (:color blue :columns 3)
      "Dumb Jump"
      ("j" dumb-jump-go "Go")
      ("o" dumb-jump-go-other-window "Other window")
      ("e" dumb-jump-go-prefer-external "Go external")
      ("x" dumb-jump-go-prefer-external-other-window "Go external other window")
      ("i" dumb-jump-go-prompt "Prompt")
      ("l" dumb-jump-quick-look "Quick look")
      ("b" dumb-jump-back "Back")))
#+END_SRC
*** yasnippet
Use snippets in specific modes
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
   :ensure t
   :init
   (setq yas-snippet-dirs
        '("~/.emacs.d/snippets"))
   :config
   (yas-global-mode 1))
#+END_SRC

Install the official snippets
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet-snippets
    :ensure t)
#+END_SRC
*** editorconfig
Use editorconfig for projects that have them

#+BEGIN_SRC emacs-lisp
  (use-package editorconfig
    :delight
    :ensure t
    :config
    (editorconfig-mode 1))
#+END_SRC
** Version Control
*** magit
use git in emacs!

=magit-yank-branch-name= is from https://emacs.stackexchange.com/questions/30487/add-copy-to-kill-ring-current-branch-name-with-magit
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t
    :general
    ("C-x g" 'magit-status)
    (my-leader-def
      "gs" 'magit-status
      "gc" 'magit-checkout
      "gC" 'magit-commit
      "gb" 'magit-blame
      "gS" 'magit-stage-file
      "gU" 'magit-unstage-file
      "gg" 'hydra-my-git-menu/body
      "gy" 'magit-yank-branch-name)
    :config
    (setq magit-completing-read-function 'ivy-completing-read)
    (defun magit-yank-branch-name ()
      "Show the current branch in the echo-area and add it to the `kill-ring'."
      (interactive)
      (let ((branch (magit-get-current-branch)))
        (if branch
            (progn (kill-new branch)
                   (message "%s" branch))
          (user-error "There is not current branch")))))
#+END_SRC

Get evil-mode to play nicely
#+BEGIN_SRC emacs-lisp
  (use-package evil-magit
    :ensure t
    :after (magit evil))
#+END_SRC
*** magithub
Press ~H~ in the magit status window to get the popup for magithub.
#+BEGIN_SRC emacs-lisp
  ;; (use-package magithub
  ;;   :after (magit)
  ;;   :ensure t
  ;;   :config
  ;;   (magithub-feature-autoinject t)
  ;;   (setq magithub-clone-default-directory "~/repos"))
#+END_SRC
*** git-timemachine
#+BEGIN_SRC emacs-lisp
  (use-package git-timemachine
    :ensure t)
#+END_SRC
*** git-messenger
Show commit info
#+BEGIN_SRC emacs-lisp
  (use-package git-messenger
    :ensure t)
#+END_SRC
*** git-gutter-fringe
Show whether something has been added, modified, or deleted on the side of the screen.

Taken from the doom-emacs config.
#+BEGIN_SRC emacs-lisp
  (use-package git-gutter-fringe
    :ensure t
    :config
    (global-git-gutter-mode 1)
    (setq-default fringes-outside-margins t)
    (define-fringe-bitmap 'git-gutter-fr:added
      [240 240 240 240 240 240 240 240 240 240 240 240 240 240]
      nil nil 'center)
    (define-fringe-bitmap 'git-gutter-fr:modified
      [240 240 240 240 240 240 240 240 240 240 240 240 240 240]
      nil nil 'center)
    (define-fringe-bitmap 'git-gutter-fr:deleted
      [0 0 0 128 192 224 240 248]
      nil nil 'center)
    (fringe-helper-define 'git-gutter-fr:added '(center repeated)
      "XXX.....")
    (fringe-helper-define 'git-gutter-fr:modified '(center repeated)
      "XXX.....")
    (fringe-helper-define 'git-gutter-fr:deleted 'bottom
      "X......."
      "XX......"
      "XXX....."
      "XXXX...."))
#+END_SRC
*** My Git Hydra
#+BEGIN_SRC emacs-lisp
  (defhydra hydra-my-git-menu (global-map "<f7>")
    "
  ^Navigate^        ^Action^               ^Info^
  ^^^^^^^^^^^^---------------------------------------------------
  _j_: next hunk    _s_: stage hunk        _d_: diff
  _k_: prev hunk    _S_: stage file        _c_: show commit
  ^ ^               _U_: unstage file      _g_: magit status
  ^ ^               ^ ^                    ^ ^
  "
    ("j" git-gutter:next-hunk)
    ("k" git-gutter:previous-hunk)
    ("s" git-gutter:stage-hunk)
    ("S" magit-stage-file)
    ("U" magit-unstage-file)
    ("c" git-messenger:popup-show)
    ("g" magit-status :exit t)
    ("d" magit-diff-buffer-file)
    ("q" quit-window "quit-window")
    ("<ESC>" git-gutter:update-all-windows "quit" :exit t))
#+END_SRC
** System Specific
*** OSX
Paths need to be explicitly defined for some reason in OSX.
=exec-path-from-shell= fixes it.
#+BEGIN_SRC emacs-lisp
  (use-package exec-path-from-shell
    :if (memq window-system '(mac ns))
    :ensure t
    :config
    (exec-path-from-shell-initialize))
#+END_SRC

Enable ligatures for fira code
#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'darwin)
    (mac-auto-operator-composition-mode))
#+END_SRC
** Mail
#+BEGIN_SRC emacs-lisp
  (use-package mu4e
    :ensure nil
    :config
    (setq mu4e-maildir "~/mail")
    (setq mu4e-sent-folder "/[Gmail].Sent Mail")
    (setq mu4e-drafts-folder "/[Gmail].Drafts")
    (setq mu4e-trash-folder "/[Gmail].Trash"))
#+END_SRC

** Other
*** restart
Yo dawg, use =restart-emacs= to restart emacs within emacs.
Using this because I'm constantly making changes to this file and sometimes I need to restart things for changes to take affect.
#+BEGIN_SRC emacs-lisp
  (use-package restart-emacs
    :ensure t)
#+END_SRC
*** multi-term
run multiple terminals at once (as opposed to =M-x term=, which can only run one terminal at a time)
#+BEGIN_SRC emacs-lisp
  (use-package multi-term
    :general
    (my-leader-def
      "tt" 'multi-term
      "tn" 'multi-term-next
      "tp" 'multi-term-prev)
    :ensure t)
#+END_SRC
*** restclient
Test RESTful APIs in emacs!
#+BEGIN_SRC emacs-lisp
  (use-package restclient
    :ensure t)

  (use-package company-restclient
    :ensure t)

  (use-package ob-restclient
    :ensure t)
#+END_SRC
*** revealjs
make reveal.js presentations in org mode
#+BEGIN_SRC emacs-lisp
  (use-package ox-reveal
    :ensure t
    :config
    (setq org-reveal-root "file:///Users/kevinpavao/reveal.js-3.8.0"))
#+END_SRC

Use python 3 by default
#+BEGIN_SRC emacs-lisp
  (when (eq system-type 'darwin)
    (setq python-shell-interpreter "/usr/local/bin/python3"))
#+END_SRC

* Languages
Configuration for programming languages
*** Python
For =flycheck= to work, install =flake8=.

LSP uses the [[https://github.com/palantir/python-language-server][palantir python language server]] (pyls).
#+BEGIN_SRC emacs-lisp
  (use-package python
    ;; :mode "\\.py\\'"
    :ghook
    ('python-mode-hook #'lsp)
    ('python-mode-hook #'smartparens-mode)
    :general
    (my-local-leader-def 'python-mode-map
      "er" 'python-shell-send-region
      "eb" 'python-shell-send-buffer
      "ef" 'python-shell-send-file
      "es" 'python-shell-send-string))
#+END_SRC

Use =pipenv= to handle virtual environments
#+BEGIN_SRC emacs-lisp
  (use-package pipenv
    :ensure t
    :hook ((python-mode . pipenv-mode)
           (hy-mode . pipenv-mode))
    :init
    (setq pipenv-projectile-after-switch-function #'pipenv-projectile-after-switch-extended))
#+END_SRC
***** Elpy - OLD
trying out LSP instead of elpy, keeping this in case I want to go back.

[[https://github.com/jorgenschaefer/elpy][elpy]] is an "Emacs Lisp Python Environment"
#+BEGIN_SRC emacs-lisp
  ;; (use-package elpy
  ;;   :ensure t
  ;;   :config
  ;;   (elpy-enable))
#+END_SRC
*** C#
#+BEGIN_SRC emacs-lisp
  ;; (use-package csharp-mode
  ;;   :ensure t
  ;;   :init
  ;;   (add-to-list 'company-backends 'company-omnisharp))

  ;; from omnisharp-emacs README
  ;; (eval-after-load
  ;;   'company
  ;;   '(add-to-list 'company-backends #'company-omnisharp))

  ;; (defun my-csharp-mode-setup ()
  ;;   (omnisharp-mode)
  ;;   (company-mode)
  ;;   (flycheck-mode)

  ;;   (setq indent-tabs-mode nil)
  ;;   (setq c-syntactic-indentation t)
  ;;   (c-set-style "ellemtel")
  ;;   (setq c-basic-offset 4)
  ;;   (setq truncate-lines t)
  ;;   (setq tab-width 4)
  ;;   (setq evil-shift-width 4)

    ;csharp-mode README.md recommends this too
    ;(electric-pair-mode 1)       ;; Emacs 24
    ;(electric-pair-local-mode 1) ;; Emacs 25

  ;;   (local-set-key (kbd "C-c r r") 'omnisharp-run-code-action-refactoring)
  ;;   (local-set-key (kbd "C-c C-c") 'recompile))

  ;; (add-hook 'csharp-mode-hook 'my-csharp-mode-setup t)
#+END_SRC
Omnisharp should load after a csharp file is loaded
#+BEGIN_SRC emacs-lisp
  ;; (use-package omnisharp
  ;;   :ensure t
  ;;   :init
  ;;   (setq omnisharp-server-executable-path "~/omnisharp-server/OmniSharp/bin/Debug/OmniSharp.exe")
  ;;   :config
  ;;  (add-hook 'csharp-mode-hook 'omnisharp-mode))
#+END_SRC
omnisharp evil-mode keys...
taken from: https://github.com/OmniSharp/omnisharp-emacs/blob/master/example-config-for-evil-mode.el
#+BEGIN_SRC emacs-lisp
  (evil-define-key 'insert omnisharp-mode-map (kbd "M-.") 'omnisharp-auto-complete)
  (evil-define-key 'normal omnisharp-mode-map (kbd "<f12>") 'omnisharp-go-to-definition)
  (evil-define-key 'normal omnisharp-mode-map (kbd "g u") 'omnisharp-find-usages)
  (evil-define-key 'normal omnisharp-mode-map (kbd "g I") 'omnisharp-find-implementations) ; g i is taken
  (evil-define-key 'normal omnisharp-mode-map (kbd "g o") 'omnisharp-go-to-definition)
  (evil-define-key 'normal omnisharp-mode-map (kbd "g r") 'omnisharp-run-code-action-refactoring)
  (evil-define-key 'normal omnisharp-mode-map (kbd "g f") 'omnisharp-fix-code-issue-at-point)
  (evil-define-key 'normal omnisharp-mode-map (kbd "g F") 'omnisharp-fix-usings)
  (evil-define-key 'normal omnisharp-mode-map (kbd "g R") 'omnisharp-rename)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", i") 'omnisharp-current-type-information)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", I") 'omnisharp-current-type-documentation)
  (evil-define-key 'insert omnisharp-mode-map (kbd ".") 'omnisharp-add-dot-and-auto-complete)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", n t") 'omnisharp-navigate-to-current-file-member)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", n s") 'omnisharp-navigate-to-solution-member)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", n f") 'omnisharp-navigate-to-solution-file-then-file-member)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", n F") 'omnisharp-navigate-to-solution-file)
  (evil-define-key 'normal omnisharp-mode-map (kbd ", n r") 'omnisharp-navigate-to-region)
  (evil-define-key 'normal omnisharp-mode-map (kbd "<f12>") 'omnisharp-show-last-auto-complete-result)
  (evil-define-key 'insert omnisharp-mode-map (kbd "<f12>") 'omnisharp-show-last-auto-complete-result)
  (evil-define-key 'normal omnisharp-mode-map (kbd ",.") 'omnisharp-show-overloads-at-point)
  (evil-define-key 'normal omnisharp-mode-map (kbd ",rl") 'recompile)

  (evil-define-key 'normal omnisharp-mode-map (kbd ",rt")
    (lambda() (interactive) (omnisharp-unit-test "single")))

  (evil-define-key 'normal omnisharp-mode-map
    (kbd ",rf")
    (lambda() (interactive) (omnisharp-unit-test "fixture")))

  (evil-define-key 'normal omnisharp-mode-map
    (kbd ",ra")
    (lambda() (interactive) (omnisharp-unit-test "all")))

  ;; Speed up auto-complete on mono drastically. This comes with the
  ;; downside that documentation is impossible to fetch.
  (setq omnisharp-auto-complete-want-documentation nil)
#+END_SRC

*** C
***** TODO set this up using use-package
Example taken from [[https://www.emacswiki.org/emacs/IndentingC][EmacsWIki: Indenting C]]
#+BEGIN_SRC emacs-lisp
  (setq c-default-style "linux"
        c-basic-offset 4)
#+END_SRC
*** Lisp
**** Keys
Keys
#+BEGIN_SRC emacs-lisp
  (my-local-leader-def
    :keymaps 'emacs-lisp-mode-map
    "eb" 'eval-buffer
    "el" 'eval-last-sexp
    "ed" 'eval-defun
    "er" 'eval-region)

  (my-local-leader-def
    :keymaps 'lisp-interaction-mode-map
    "eb" 'eval-buffer
    "el" 'eval-last-sexp
    "ed" 'eval-defun
    "er" 'eval-region)

  (my-local-leader-def
    :keymaps 'lisp-mode-map
    "er" 'eval-region
    "ed" 'eval-defun)

  (my-local-leader-def
    :keymaps 'scheme-mode-map
    "r" 'run-geiser
    "er" 'geiser-eval-region
    "eR" 'geiser-eval-region-and-go
    "eb" 'geiser-eval-buffer
    "eB" 'geiser-eval-buffer-and-go
    "ed" 'geiser-eval-definition
    "eD" 'geiser-eval-definition-and-go
    "el" 'geiser-eval-eval-sexp)
#+END_SRC
**** Shared
#+BEGIN_SRC emacs-lisp
  (defconst my-lisp-mode-hooks
    '(lisp-mode-hook
      emacs-lisp-mode-hook
      scheme-mode-hook
      geiser-repl-mode-hook
      hy-mode-hook
      inferior-hy-mode-hook
      clojure-mode-hook))
#+END_SRC

- =show-paren-mode= highlights matching parentheses
- =paredit= inserts matching parentheses, among other things..
#+BEGIN_SRC emacs-lisp
  (setq show-paren-delay 0)
  (show-paren-mode 1)

  ;; (use-package paredit
  ;;   :ensure t
  ;;   :init
  ;;   (add-hook 'emacs-lisp-mode-hook #'enable-paredit-mode)
  ;;   (add-hook 'lisp-mode-hook #'enable-paredit-mode)
  ;;   (add-hook 'hy-mode-hook #'enable-paredit-mode)
  ;;   (add-hook 'inferior-hy-mode-hook #'enable-paredit-mode)
  ;;   (add-hook 'scheme-mode-hook #'enable-paredit-mode)
  ;;   (add-hook 'geiser-repl-mode-hook #'enable-paredit-mode))

  (use-package lispy
    :ensure t
    :ghook my-lisp-mode-hooks)

  (add-hook 'emacs-lisp-mode-hook 'turn-on-eldoc-mode)
  (add-hook 'lisp-interaction-mode-hook 'turn-on-eldoc-mode)
  (add-hook 'ielm-mode-hook 'turn-on-eldoc-mode)
#+END_SRC
**** Scheme
=geiser= provides a nice repl for *scheme* and other things
#+BEGIN_SRC emacs-lisp
  (use-package geiser
    :ensure t
    :config
    (setq geiser-active-implementations '(guile mit racket)))
#+END_SRC
**** Common Lisp
Using this to mess with stumpwm right now.
#+BEGIN_SRC emacs-lisp
  ;; (use-package slime
  ;;   :ensure t
  ;;   :init
  ;;   (setq inferior-list-program "sbcl"))
#+END_SRC
**** Hy
Let's get hy. A lisp for Python.
#+BEGIN_SRC emacs-lisp
  (use-package hy-mode
    :ensure t
    :mode "\\.hy\\'"
    :general
    (my-local-leader-def 'hy-mode-map
      "er" 'hy-shell-eval-region
      "eb" 'hy-shell-eval-buffer
      "el" 'hy-shell-eval-last-sexp
      "ed" 'hy-shell-eval-current-form))
#+END_SRC
**** Clojure
#+BEGIN_SRC emacs-lisp
  (use-package clojure-mode
    :ensure t)
#+END_SRC
*** Haskell
For xmonad and beyond
#+BEGIN_SRC emacs-lisp
  (use-package haskell-mode
    :ensure t
    :mode "\\.hs\\'"
    :hook (haskell-mode . turn-on-haskell-indent))
#+END_SRC
*** Javascript
**** Vanilla
Setup for JavaScript using =js2-mode=.

- autocomplete with =tern=
- using =tide= for:
  + info in the minibuffer about the highlighted item
  + jump to defifinition / implementation
  + linting
- prettify the file on save using =prettier-js= along with =prettier=
- add =eslint= to =flycheck= for linting

Largely stolen from https://github.com/CSRaghunandan/.emacs.d/blob/master/setup-files/setup-js.el
#+BEGIN_SRC emacs-lisp
  (use-package js2-mode
    :ensure t
    :mode (("\\.js$" . js2-mode))
    :hook (js2-mode . my-js-hook)
    :ensure-system-package ((prettier . "npm i -g prettier")
                            (eslint . "npm i -g eslint")
                            (eslint_d . "npm i -g eslint_d"))
    :preface
    (defun my-tide-setup-hook ()
      "Configure tide"
      (tide-setup)
      ;; highlight identifiers
      (tide-hl-identifier-mode +1)
      (eldoc-mode t)
      (flycheck-mode t)
      ;; configure javascript-tide checker to run after your default javascript checker
      (flycheck-add-next-checker 'javascript-eslint 'javascript-tide 'append)
      ;; (prettier-js-mode)
      )

    ;; TODO make this work with eslint
    ;; (defun my-lsp-js-setup-hook ()
    ;;   "Fix company completions for the LSP and then enable it"
    ;;   (defun my-company-transformer (candidates)
    ;;     (let ((completion-ignore-case t))
    ;;       (all-completions (company-grab-symbol) candidates)))
    ;;   (make-local-variable 'company-transformers)
    ;;   (push 'my-company-transformer company-transformers)
    ;;   (lsp-javascript-typescript-enable))

    (defun my-js-hook ()
      "Set up JavaScript"
      ;; set evil indent, ">>", to 2
      (setq evil-shift-width js-indent-level)
      (my-tide-setup-hook)
      ;; (my-lsp-js-setup-hook)
      (tern-mode t)
      (smartparens-mode t))
    :init
    ;; set the indent level to 2
    (setq js2-basic-offset 4)
    (setq js-chain-indent t)
    (setq js-indent-level 4)

    ;; use eslint_d instead of eslint for faster linting
    (setq flycheck-javascript-eslint-executable "eslint_d")

    ;; highlight most ECMA built-ins
    (setq js2-highlight-level 3)

    ;; turn off all warnings in js2-mode
    (setq js2-mode-show-parse-errors t)
    (setq js2-mode-show-strict-warnings nil)
    (setq js2-strict-missing-semi-warning nil))
#+END_SRC

=tern= and =tern-company= are for auto completion
#+BEGIN_SRC emacs-lisp
  (use-package tern
    :ensure t
    :ensure-system-package ((tern . "npm i -g tern"))
    :init
    (setq tern-command '("/home/kevin/.node_modules/bin/tern")))

  (use-package company-tern
    :ensure t
    :config
    (add-to-list 'company-backends 'company-tern))
#+END_SRC

Set up javascript with LSP
#+BEGIN_SRC emacs-lisp
  ;; (use-package lsp-javascript-typescript
  ;;   :ensure t
  ;;   :ensure-system-package ((javascript-typescript-langserver . "npm i -g javascript-typescript-langserver")))
#+END_SRC

Set up =tide-mode=
#+BEGIN_SRC emacs-lisp
  (use-package tide
    :ensure t
    :after (js2-mode company flycheck))
#+END_SRC

Set up =prettier-js-mode=
#+BEGIN_SRC emacs-lisp
  ;; (use-package prettier-js
  ;;   :ensure t
  ;;   :hook ((js2-mode . prettier-js-mode)
  ;;          (rjsx-mode . prettier-js-mode)))
#+END_SRC

**** JSON
#+BEGIN_SRC emacs-lisp
  (use-package json-mode
    :ensure t
    :mode "\\.json\\'")
#+END_SRC
**** TODO TypeScript
#+BEGIN_SRC emacs-lisp
  ;; (use-package tide
  ;;   :ensure t
  ;;   :config
  ;;   ;; aligns annotation to the right hand side
  ;;   (setq company-tooltip-align-annotations t)
  ;;   ;; formats the buffer before saving
  ;;   (add-hook 'before-save-hook 'tide-format-before-save)
  ;;   (add-hook 'typescript-mode-hook
  ;;             (lambda ()
  ;;               (interactive)
  ;;               (tide-setup)
  ;;               (flycheck-mode +1)
  ;;               (setq flycheck-check-syntax-automatically '(save-mode-enabled))
  ;;               (eldoc-mode +1)
  ;;               (tide-hl-identifier-mode +1)))
  ;;   (add-hook 'tide-mode-hook
  ;;             (lambda ()
  ;;               (define-key tide-mode-map (kbd "<f12>") 'tide-jump-to-definition))))
#+END_SRC
**** React
=rjsx-mode= is for editing =.jsx= files

Dont need too much here because it uses =js2-mode= where most of the config is done
#+BEGIN_SRC emacs-lisp
  (use-package rjsx-mode
    :ensure t
    :mode "\\.jsx\\'")
#+END_SRC
*** Web Mode
Set up web mode for html and css files
#+BEGIN_SRC emacs-lisp
  (use-package web-mode
    :ensure t
    :preface
    (defun my-web-mode-hook ()
      ;; set the html indent to 2
      (setq web-mode-markup-indent-offset 2)
      (setq evil-shift-width 2)
      ;; highlight matching elements in html
      (setq web-mode-enable-current-element-highlight 1))
    :hook (web-mode . my-web-mode-hook)
    :init
    ;; (setq web-mode-ac-sources-alist
    ;;       '(("css" . (ac-source-css-property))
    ;;         ("html" . (ac-source-words-in-buffer ac-source-abbrev))))
    (add-hook 'web-mode-before-auto-complete-hooks
              '(lambda ()
                 (let ((web-mode-cur-language
                        (web-mode-language-at-pos))))))
    (add-to-list `auto-mode-alist '("\\.html?\\'" . web-mode))
    (add-to-list `auto-mode-alist '("\\.css\\'" . web-mode)))
#+END_SRC
*** PHP
#+BEGIN_SRC emacs-lisp
  (use-package php-mode
    :ensure t
    :mode "\\.php\\'"
    :hook (php-mode . my-php-hook)
    :preface
    (defun my-php-hook ()
      (php-enable-default-coding-style)
      (smartparens-mode t))
    (defun my/align-php-dbl-arrow ()
      "Align the => in arrays."
      (interactive)
      (align-regexp
       (region-beginning) (region-end)
       "\\(\\s-*\\) => " 1 0 nil))
    :general
    (general-define-key
     :keymaps 'php-mode-map
     "C-c a" 'my/align-php-dbl-arrow)
    (my-local-leader-def 'php-mode-map
      "a" 'my/align-php-dbl-arrow
      "j" 'ac-php-find-symbol-at-point)
    :config
    ;; align -> on successive lines
    (setq php-lineup-cascaded-calls t)
    (setq flycheck-phpcs-standard "WellspringCodingStandard"))
#+END_SRC

Documentation in the minibuffer and with =company=. This is needed by =company-php=.
#+BEGIN_SRC emacs-lisp
  (use-package php-eldoc
    :ensure t
    :after (php-mode))
#+END_SRC

Setup code completion and documentation.
#+BEGIN_SRC emacs-lisp
  (use-package company-php
    :ensure t
    :after (php-eldoc)
    :hook (php-mode . my-company-php-hook)
    :preface
    (defun my-company-php-hook ()
      (ac-php-core-eldoc-setup)
      (make-local-variable 'company-backends)
      (add-to-list 'company-backends 'company-ac-php-backend)))
#+END_SRC

Use =PHP_CodeSniffer= to format files on save.
*NOTE* removing format on save (for now) as it messes with undo history.
#+BEGIN_SRC emacs-lisp
  (use-package phpcbf
    :ensure t
    :after (php-mode)
    ;;:hook ((php-mode . phpcbf-enable-on-save))
    :config
    (setq phpcbf-executable "/usr/local/bin/phpcbf")
    (setq phpcbf-standard "WellspringCodingStandard"))
#+END_SRC
* TODO Things to do
An on-going list of things I want to change

- [X] fix evil escape keys
  - using the =evil-collection= package
- [ ] make org prettier?
  + [ ] bullets?
- yasnippet: [2/2]
  + [X] learn to use
  + [X] configure
- [ ] Configure C#
  + use the C# lsp??
- [ ] fix =eslint= for lsp if possible
  + eslint works fine without the =lsp-javascript-typescript=
- [ ] setup =forge= to replace =magithub=
- [ ] window management hydra?
- [-] telephone-line [1/6]
  + [-] my-buffer-segment [2/3]
    + [X] display truncated path up to project name, full path up to file name
    + [X] color project name
    + [ ] different colors for path / file name?
  + [ ] fix colors
  + [X] git
  + [ ] eyebrowse
  + [ ] anzu
  + [ ] flycheck
- [ ] make jumping better
  - [ ] use 'ac' package jumps along with smart and dumb jump?
  - [ ] make keybindings consistent

** Cool looking packages to check out
- =straight.el= - https://github.com/raxod502/straight.el
  - package management
- =purpose= - https://github.com/bmag/emacs-purpose
  - window/buffer management
- =multiple-cursors= - https://github.com/magnars/multiple-cursors.el
- =iedit= - https://github.com/victorhge/iedit
  - like multiple cursors
- =eglot= - https://github.com/joaotavora/eglot
  - lightweight LSP
- =targets= - https://github.com/noctuid/targets.el
  - operate on text objects
- =git-gitter=
- =diff-hl= - like =git-gutter=
- =shackle= - https://github.com/wasamasa/shackle
  - control popup windows
- =smart-mode-line=
- =minions=
  - minor modes in the modeline?
- =moody=
  - powerline-esque modeline
- =github-notifier= - https://github.com/xuchunyang/github-notifier.el
  - github notification count in the modeline
- =evil-escape=
- =evil-indent=
- =emacs-libvterm= - https://github.com/akermu/emacs-libvterm
- =lispyville= - safe paren editing for evil, uses lispy?
- =prescient= - sorts candiates in ivy, company, etc

